// Python-parity test: the JS engine must reproduce the archived Python
// classifier's output on the golden corpus (generated by
// archive/flask-app/tools/dump_golden.py).
//
// This test exists only for the porting phase. Once accuracy work
// intentionally diverges from the Python behavior, delete this file — the
// corpus expectation tests (corpus.test.mjs) remain the source of truth.

import test from "node:test";
import assert from "node:assert/strict";

import { classifyText } from "../js/engine/classify.js";
import { loadCorpusCases, loadGolden } from "./helpers.mjs";

// Differences from Python that are understood and accepted. Keyed by
// `${caseId}` with a reason; matching failures are reported but not fatal.
//
// The "unglued citation sentence" group: NLTK punkt over-split inside rule
// citations ("Under Fed." / "U.S.C."), and the Python merge pass then glued
// the fragments BACKWARD into the preceding sentence whenever that sentence
// itself contained a citation — fusing a real "Under [rule], …" rule sentence
// onto the preceding issue/conclusion sentence. The JS segmenter never makes
// the bogus split, so it keeps the true sentence boundary. The JS output is
// more correct; sentence counts (and thus downstream fields) differ.
const UNGLUED = "JS keeps a real sentence boundary that punkt+merge fused";
const KNOWN_DIFFS = new Map([
  ["model-answers-v2/II-Q2", UNGLUED],
  ["model-answers-v2/E2-S2", UNGLUED],
  ["model-answers-v2/E2-S3", UNGLUED],
  ["model-answers-v2/E2-S4", UNGLUED],
  ["model-answers-v2/E2-S5", UNGLUED],
  ["model-answers-v2/E2-S6", UNGLUED],
]);

// Party-name triggers depend on set iteration order (nondeterministic in
// Python); normalize them before comparison.
function normalizeTrigger(trigger) {
  if (typeof trigger !== "string") return trigger;
  if (trigger.startsWith("[party:")) return "[party:*]";
  return trigger;
}

const corpus = loadCorpusCases();
const golden = loadGolden();

test("golden corpus is available", () => {
  assert.ok(corpus.length >= 40, `expected ≥40 corpus cases, got ${corpus.length}`);
  assert.ok(Object.keys(golden).length >= 40, "expected golden output");
});

for (const corpusCase of corpus) {
  const expected = golden[corpusCase.id];
  if (!expected) continue;

  test(`parity: ${corpusCase.id}`, (t) => {
    const known = KNOWN_DIFFS.get(corpusCase.id);
    const actual = classifyText(corpusCase.paragraphs, corpusCase.framework);

    const fail = (msg) => {
      if (known) {
        t.diagnostic(`known diff (${known}): ${msg}`);
        return;
      }
      assert.fail(msg);
    };

    if (actual.paragraphs.length !== expected.paragraphs.length) {
      fail(
        `paragraph count ${actual.paragraphs.length} != ${expected.paragraphs.length}`
      );
      return;
    }

    expected.paragraphs.forEach((expPara, pi) => {
      const actPara = actual.paragraphs[pi];

      // Segmentation parity first — most drift starts here.
      const expTexts = expPara.sentences.map((s) => s.text);
      const actTexts = actPara.sentences.map((s) => s.text);
      if (JSON.stringify(expTexts) !== JSON.stringify(actTexts)) {
        fail(
          `¶${pi} segmentation differs:\n  python: ${JSON.stringify(expTexts, null, 1)}\n  js:     ${JSON.stringify(actTexts, null, 1)}`
        );
        return;
      }

      // Framework + badge
      if (actPara.effective_framework !== expPara.effective_framework) {
        fail(
          `¶${pi} framework ${actPara.effective_framework} != ${expPara.effective_framework}`
        );
      }
      if (actPara.badge !== expPara.badge) {
        fail(`¶${pi} badge ${actPara.badge} != ${expPara.badge}`);
      }
      if (actPara.structure_score !== expPara.structure_score) {
        fail(
          `¶${pi} structure_score ${actPara.structure_score} != ${expPara.structure_score}`
        );
      }

      // Per-sentence labels and diagnostics
      expPara.sentences.forEach((expSent, si) => {
        const actSent = actPara.sentences[si];
        const where = `¶${pi} s${si} "${expSent.text.slice(0, 60)}"`;

        if (actSent.label !== expSent.label) {
          fail(
            `${where}: label ${actSent.label} != ${expSent.label} (js trigger: ${actSent.trigger_phrase}, py trigger: ${expSent.trigger_phrase})`
          );
        }
        if (
          normalizeTrigger(actSent.trigger_phrase) !== normalizeTrigger(expSent.trigger_phrase)
        ) {
          fail(
            `${where}: trigger "${actSent.trigger_phrase}" != "${expSent.trigger_phrase}"`
          );
        }
        if (actSent.blend !== expSent.blend) {
          fail(`${where}: blend ${actSent.blend} != ${expSent.blend}`);
        }
        if (actSent.counterargument !== expSent.counterargument) {
          fail(
            `${where}: counterargument ${actSent.counterargument} != ${expSent.counterargument}`
          );
        }
        if (Math.abs(actSent.confidence - expSent.confidence) > 0.015) {
          fail(
            `${where}: confidence ${actSent.confidence} != ${expSent.confidence}`
          );
        }
        if (actSent.confidence_label !== expSent.confidence_label) {
          fail(
            `${where}: band ${actSent.confidence_label} != ${expSent.confidence_label}`
          );
        }

        // Evidence scores (tolerant float comparison)
        for (const [label, expScore] of Object.entries(expSent.evidence_scores || {})) {
          const actScore = actSent.evidence_scores?.[label] ?? 0;
          if (Math.abs(actScore - expScore) > 0.011) {
            fail(`${where}: evidence_scores[${label}] ${actScore} != ${expScore}`);
          }
        }
      });

      // Revision priorities: kinds in order
      const expKinds = (expPara.revision_priorities || []).map((p) => p.kind);
      const actKinds = (actPara.revision_priorities || []).map((p) => p.kind);
      if (JSON.stringify(expKinds) !== JSON.stringify(actKinds)) {
        fail(`¶${pi} priorities ${actKinds} != ${expKinds}`);
      }
    });

    // Summary parity
    if (actual.summary.total_sentences !== expected.summary.total_sentences) {
      fail(
        `summary.total_sentences ${actual.summary.total_sentences} != ${expected.summary.total_sentences}`
      );
    }
  });
}
