import io
import os
import sys

from docx import Document
from werkzeug.datastructures import FileStorage

sys.path.insert(0, os.path.dirname(__file__))

from app import app
from app import exporter, parser
from app.classifier import classify_text
from app.constants import MAX_PASTE_BYTES, MAX_UPLOAD_BYTES


def test_plaintext_and_rtf_parser_paths():
    text = "Rule: Battery requires harmful or offensive contact.\n\nAnalysis: Dana shoved Lee."
    paragraphs, warnings = parser.parse_plaintext(text)
    assert warnings == []
    assert len(paragraphs) == 1
    assert "Battery requires" in paragraphs[0]

    raw = b"{\\rtf1\\ansi Rule: Battery requires contact.\\par Here, Dana shoved Lee.}"
    upload = FileStorage(stream=io.BytesIO(raw), filename="draft.rtf")
    paragraphs, warnings = parser.parse_rtf(upload)
    assert warnings == []
    assert any("Battery requires contact" in para for para in paragraphs)


def test_docx_parser_reads_nonempty_document():
    buf = io.BytesIO()
    doc = Document()
    doc.add_paragraph("Rule: Battery requires harmful or offensive contact.")
    doc.add_paragraph("Here, Dana shoved Lee.")
    doc.save(buf)
    buf.seek(0)

    upload = FileStorage(stream=buf, filename="draft.docx")
    paragraphs, warnings = parser.parse_docx(upload)
    assert warnings == []
    assert paragraphs
    assert "Battery requires" in paragraphs[0]


def test_analyze_rejects_oversized_paste():
    client = app.test_client()
    too_large = "a" * (MAX_PASTE_BYTES + 1)
    response = client.post("/analyze", json={"text": too_large, "framework": "AUTO"})
    assert response.status_code == 400
    assert response.get_json()["error"] == "Pasted text is too long. Please keep pasted text under 50KB."


def test_analyze_rejects_non_string_paste():
    client = app.test_client()
    response = client.post("/analyze", json={"text": {"bad": "shape"}, "framework": "AUTO"})
    assert response.status_code == 400
    assert response.get_json()["error"] == "No text was provided. Please paste text or upload a file."


def test_analyze_rejects_oversized_upload():
    client = app.test_client()
    response = client.post(
        "/analyze",
        data={
            "framework": "AUTO",
            "file": (io.BytesIO(b"x" * (MAX_UPLOAD_BYTES + 1)), "draft.rtf"),
        },
        content_type="multipart/form-data",
    )
    assert response.status_code == 400
    assert response.get_json()["error"] == "Uploaded file is too large. Please keep uploads under 10MB."


def test_analyze_rejects_unsupported_upload_type():
    client = app.test_client()
    response = client.post(
        "/analyze",
        data={
            "framework": "AUTO",
            "file": (io.BytesIO(b"not a legal draft"), "draft.txt"),
        },
        content_type="multipart/form-data",
    )
    assert response.status_code == 400
    assert response.get_json()["error"] == "Unsupported file type. Please upload a .docx, .pdf, or .rtf file."


def test_rtf_upload_route_works():
    client = app.test_client()
    raw = b"{\\rtf1\\ansi Rule: Battery requires contact.\\par Here, Dana shoved Lee.}"
    response = client.post(
        "/analyze",
        data={"framework": "AUTO", "file": (io.BytesIO(raw), "draft.rtf")},
        content_type="multipart/form-data",
    )
    assert response.status_code == 200
    data = response.get_json()
    assert data["paragraphs"]
    labels = [sent["label"] for sent in data["paragraphs"][0]["sentences"]]
    assert "RULE" in labels


def test_export_docx_contains_structured_feedback():
    data = classify_text([
        "Here, Dana shoved Lee during the argument. Therefore, Dana is likely liable."
    ], "AUTO")
    buf = exporter.export_docx(data)
    doc = Document(buf)
    text = "\n".join(p.text for p in doc.paragraphs)
    assert "Annotated Legal Draft" in text
    assert "Generated by Legal Writing Structure Coach" in text
    assert "Avg confidence" in text
    assert "Application needs a legal anchor" in text
    assert "Low confidence" in text or "Warning" in text


def test_export_route_hides_internal_exception(monkeypatch):
    def boom(_data):
        raise RuntimeError("sensitive internal detail")

    monkeypatch.setattr(exporter, "export_docx", boom)
    response = app.test_client().post("/export", json={"paragraphs": []})
    assert response.status_code == 500
    assert "sensitive internal detail" not in response.get_json()["error"]
