// Annotated .docx export, generated entirely in the browser via the vendored
// docx library. Port of the archived Python exporter: same highlight palette
// (python-docx WD_COLOR_INDEX names → OOXML highlight names), same badge /
// coaching / summary layout. Manually corrected sentences get a ✎ marker.

let docxLoading = null;

function loadDocxLib() {
  if (window.docx) return Promise.resolve(window.docx);
  if (!docxLoading) {
    docxLoading = new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = "./js/vendor/docx/docx.iife.js";
      script.onload = () => resolve(window.docx);
      script.onerror = () => reject(new Error("could not load the document writer"));
      document.head.appendChild(script);
    });
  }
  return docxLoading;
}

// Label → OOXML highlight name (mirrors python-docx WD_COLOR_INDEX choices).
const HIGHLIGHT_MAP = {
  ISSUE: "magenta",
  RULE: "green",
  EXPLANATION: "darkMagenta",
  APPLICATION: "darkYellow",
  CONCLUSION: "cyan",
  UNCLASSIFIED: null,
};

const BLEND_COLOR = "FF0000";

function avgConfidence(sentences) {
  const values = sentences
    .map((s) => s.confidence)
    .filter((v) => typeof v === "number");
  if (!values.length) return null;
  return Math.round((values.reduce((a, b) => a + b, 0) / values.length) * 100);
}

/** Build the annotated document and return it as a Blob (no download). */
export async function buildDocxBlob(results, correctionCount = 0) {
  const docx = await loadDocxLib();
  const { Document, Packer, Paragraph, TextRun, HeadingLevel } = docx;

  const children = [];

  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: "Annotated Legal Draft", size: 28 })],
    })
  );

  let subtitle =
    `Framework: ${results.framework || "AUTO"}  |  ` +
    "Generated by Legal Writing Structure Practice";
  if (correctionCount > 0) {
    subtitle += `  |  ${correctionCount} label${correctionCount === 1 ? "" : "s"} set manually (marked ✎)`;
  }
  children.push(
    new Paragraph({
      children: [new TextRun({ text: subtitle, size: 18, italics: true })],
    })
  );
  children.push(new Paragraph({}));

  for (const para of results.paragraphs || []) {
    let badgeLabel = para.badge_label || "";
    const sentences = para.sentences || [];
    const avg = avgConfidence(sentences);
    if (avg !== null) badgeLabel += `  |  Avg confidence: ${avg}%`;
    if (typeof para.structure_score === "number") {
      badgeLabel += `  |  Structure: ${para.structure_score}/100`;
    }

    const badgeRuns = [
      new TextRun({ text: badgeLabel, bold: true, italics: true, size: 18 }),
    ];
    if (para.suggestion) {
      badgeRuns.push(new TextRun({ text: "  " }));
      badgeRuns.push(new TextRun({ text: para.suggestion, italics: true, size: 16 }));
    }
    children.push(new Paragraph({ children: badgeRuns }));

    if (para.training_summary) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: para.training_summary, italics: true, size: 16 })],
        })
      );
    }

    for (const item of (para.revision_priorities || []).slice(0, 3)) {
      const title = item.title || item.kind || "Revision priority";
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [
            new TextRun({ text: `${title} `, bold: true, size: 16 }),
            new TextRun({ text: item.detail || "", size: 16 }),
          ],
        })
      );
    }

    // Content paragraph — one docx paragraph per source paragraph.
    const contentRuns = [];
    sentences.forEach((sent, i) => {
      const opts = { text: sent.text, size: 22 };
      const highlight = HIGHLIGHT_MAP[sent.label];
      if (highlight) opts.highlight = highlight;
      if (sent.blend) opts.color = BLEND_COLOR;
      if (sent.confidence_label === "low") opts.italics = true;
      if (sent.revision_hint && ["low", "medium"].includes(sent.confidence_label)) {
        opts.underline = {};
      }
      contentRuns.push(new TextRun(opts));
      if (sent.corrected) {
        contentRuns.push(new TextRun({ text: "✎", size: 22, superScript: true }));
      }
      if (i < sentences.length - 1) contentRuns.push(new TextRun({ text: " ", size: 22 }));
    });
    children.push(new Paragraph({ children: contentRuns }));
    children.push(new Paragraph({}));
  }

  // Summary section
  const summary = results.summary || {};
  if (Object.keys(summary).length) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Analysis Summary" })],
      })
    );
    const rows = [
      ["Paragraphs analyzed", summary.total_paragraphs ?? 0],
      ["Complete paragraphs", summary.complete_paragraphs ?? 0],
      ["Warning paragraphs", summary.warning_paragraphs ?? 0],
      ["Total sentences", summary.total_sentences ?? 0],
      ["Blended sentences", summary.blend_count ?? 0],
    ];
    for (const [label, count] of Object.entries(summary.label_counts || {})) {
      rows.push([`  ${label}`, count]);
    }
    for (const [label, value] of rows) {
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [
            new TextRun({ text: `${label}: `, bold: true }),
            new TextRun({ text: String(value) }),
          ],
        })
      );
    }
  }

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBlob(doc);
}

/** Build the annotated document and download it. */
export async function exportDocx(results, correctionCount = 0) {
  const blob = await buildDocxBlob(results, correctionCount);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "annotated_draft.docx";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
