"""
Annotated .docx export.
Accepts the full /analyze JSON response and returns a BytesIO of the .docx.
"""

from io import BytesIO

from docx import Document
from docx.enum.text import WD_COLOR_INDEX
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Pt, RGBColor

# Map label → WD_COLOR_INDEX value
HIGHLIGHT_MAP = {
    "ISSUE":        WD_COLOR_INDEX.PINK,
    "RULE":         WD_COLOR_INDEX.BRIGHT_GREEN,
    "EXPLANATION":  WD_COLOR_INDEX.VIOLET,
    "APPLICATION":  WD_COLOR_INDEX.DARK_YELLOW,
    "CONCLUSION":   WD_COLOR_INDEX.TURQUOISE,
    "UNCLASSIFIED": None,
}

BLEND_COLOR = RGBColor(0xFF, 0x00, 0x00)


def _add_badge_paragraph(
    doc: Document,
    badge_label: str,
    suggestion: str,
    training_summary: str = "",
    revision_priorities: list[dict] | None = None,
) -> None:
    """Add a compact coaching header with optional revision priorities."""
    para = doc.add_paragraph()
    run = para.add_run(badge_label)
    run.bold = True
    run.italic = True
    run.font.size = Pt(9)

    if suggestion:
        para.add_run("  ")
        sugg_run = para.add_run(suggestion)
        sugg_run.italic = True
        sugg_run.font.size = Pt(8)

    if training_summary:
        summary_para = doc.add_paragraph()
        summary_run = summary_para.add_run(training_summary)
        summary_run.font.size = Pt(8)
        summary_run.italic = True

    for item in (revision_priorities or [])[:3]:
        p = doc.add_paragraph(style="List Bullet")
        p.clear()
        title = item.get("title") or item.get("kind") or "Revision priority"
        detail = item.get("detail") or ""
        p.add_run(f"{title}: ").bold = True
        p.add_run(detail)
        for run in p.runs:
            run.font.size = Pt(8)


def _avg_confidence(sentences: list[dict]) -> int | None:
    values = [
        sent.get("confidence")
        for sent in sentences
        if isinstance(sent.get("confidence"), (int, float))
    ]
    if not values:
        return None
    return round(sum(values) / len(values) * 100)


def export_docx(classification_data: dict) -> BytesIO:
    """
    Build an annotated .docx from classification data and return a BytesIO.
    """
    doc = Document()

    # Title
    title = doc.add_heading("Annotated Legal Draft", level=1)
    title.runs[0].font.size = Pt(14)
    subtitle = doc.add_paragraph(
        f"Framework: {classification_data.get('framework', 'IRAC')}  |  "
        f"Generated by IRAC/CREAC Structural Highlighter"
    )
    subtitle.runs[0].font.size = Pt(9)
    subtitle.runs[0].italic = True
    doc.add_paragraph()  # spacer

    for para_data in classification_data.get("paragraphs", []):
        badge_label = para_data.get("badge_label", "")
        suggestion = para_data.get("suggestion", "")
        sentences = para_data.get("sentences", [])
        avg_conf = _avg_confidence(sentences)
        if avg_conf is not None:
            badge_label = f"{badge_label}  |  Avg confidence: {avg_conf}%"
        if isinstance(para_data.get("structure_score"), int):
            badge_label = f"{badge_label}  |  Structure: {para_data['structure_score']}/100"

        # Badge line
        _add_badge_paragraph(
            doc,
            badge_label,
            suggestion,
            para_data.get("training_summary", ""),
            para_data.get("revision_priorities", []),
        )

        # Content paragraph — one docx paragraph per source paragraph
        content_para = doc.add_paragraph()
        sentences = para_data.get("sentences", [])

        for i, sent in enumerate(sentences):
            text = sent["text"]
            label = sent["label"]
            is_blend = sent.get("blend", False)

            run = content_para.add_run(text)
            run.font.size = Pt(11)

            # Highlight color
            highlight = HIGHLIGHT_MAP.get(label)
            if highlight is not None:
                run.font.highlight_color = highlight

            # Blend: red font color
            if is_blend:
                run.font.color.rgb = BLEND_COLOR

            if sent.get("confidence_label") == "low":
                run.italic = True

            if sent.get("revision_hint") and sent.get("confidence_label") in ("low", "medium"):
                run.font.underline = True

            # Space between sentences
            if i < len(sentences) - 1:
                content_para.add_run(" ")

        doc.add_paragraph()  # blank line between paragraphs

    # Summary section
    summary = classification_data.get("summary", {})
    if summary:
        doc.add_heading("Analysis Summary", level=2)
        rows = [
            ("Paragraphs analyzed", summary.get("total_paragraphs", 0)),
            ("Complete paragraphs", summary.get("complete_paragraphs", 0)),
            ("Warning paragraphs", summary.get("warning_paragraphs", 0)),
            ("Total sentences", summary.get("total_sentences", 0)),
            ("Blended sentences", summary.get("blend_count", 0)),
        ]
        label_counts = summary.get("label_counts", {})
        for lbl, count in label_counts.items():
            rows.append((f"  {lbl}", count))

        for label_text, value in rows:
            p = doc.add_paragraph(style="List Bullet")
            p.clear()
            p.add_run(f"{label_text}: ").bold = True
            p.add_run(str(value))

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
